server {
    listen 80;
    server_name kinerja.orb.local kinerja.localhost;
    root /var/www/kinerja/public;
    index index.php index.html;

    # Logging
    access_log /var/log/nginx/laravel-app.access.log;
    error_log /var/log/nginx/laravel-app.error.log;

    # Laravel routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass kinerja-app-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # Block hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Upload size
    client_max_body_size 100M;
}
